server:
  port: 9090
spring:
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/ucareer?serverTimezone=GMT%2b8
   username: root
   password: 12345678
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

app:
  upload:
    dir: /upload/

